# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1902.01"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.cpus = "2"
  end
   config.vm.provision "shell", inline: <<-SHELL
       sudo yum install ansible -y
       ansible-playbook /vagrant/main.yml
   SHELL
end
