# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1902.01"
  config.vm.host_name = "otus-centos"

  config.vm.network "private_network", ip: "192.168.10.50"

   config.vm.provider "virtualbox" do |vb|
     vb.name = "otus-centos-ansible"
     vb.memory = "512"
     vb.cpus = "1"
   end
   config.vm.provision "shell", inline: <<-SHELL
     cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
   SHELL
end
